version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: sgepd-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mouad3at3at
    ports:
      - "5432:5432"
    volumes:
      - sgepd-db-data:/var/lib/postgresql
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  sgepd-db-data:
