<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.digitello</groupId>
    <artifactId>sgepd-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>auth-service</module>
        <module>user-service</module>
        <module>screen-service</module>
        <module>client-service</module>
        <module>ticket-service</module>
        <module>assignment-service</module>
        <module>dashboard-service</module>
        <module>location-service</module>
        <module>api-gateway</module>
    </modules>
</project>
